services:
  app:
    # They pull directly from your GitHub Package registry
    image: ghcr.io/thegabeman/chargelogreporter:latest
    container_name: charge-log-reporter
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./database:/database
    restart: always