version: "3"
services:
    chargelogreporter:
        ports:
            - 5000:5000
        container_name: chargelogreporter
        volumes:
            - $(pwd)/.env:/.env
            - $(pwd)/database:/database
        image: chargelogreporter:latest
